---
abstract: 'Opinionated Modern Perl Development Framework'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires:
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bubblegum
requires:
  Class::Load: '0.21'
  Exporter::Tiny: '0.030'
  IPC::System::Simple: '1.25'
  Import::Into: '1.001001'
  Moo: '1.003001'
  Syntax::Keyword::Junction: '0.003007'
  Throwable: '0.200011'
  Type::Tiny: '0.032'
  autobox: '0'
  autodie: '0'
  namespace::autoclean: '0.19'
  perl: v5.10.0
  utf8::all: '0'
resources:
  bugtracker: https://github.com/alnewkirk/Bubblegum/issues
  homepage: http://metacpan.org/release/Bubblegum/
  repository: git://github.com/alnewkirk/Bubblegum.git
version: '0.34'
x_authority: cpan:AWNCORP
x_contributors:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'Сергей Романов <sromanov-dev@yandex.ru>'
