#!/usr/bin/env perl

BEGIN {
    use FindBin;
    use lib $FindBin::Bin . '/../lib';
}

# ADD -SHORT SUFFIX TO GENERATED TYPES AND TYPEOFS FOR CONVENIENCE.
package BankAccount;

use Bubblegum::Class;
use Bubblegum::Syntax -minimal;

has _num, 'balance';

sub deposit {
    my $self    = _obj shift;
    my $amount  = _num shift;

    return $self->balance + $amount;
}

my $account = BankAccount->new(balance => 1000);
say $account->deposit(@ARGV);
